# Generated by Django 3.2.8 on 2022-02-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('area', models.IntegerField()),
                ('mt_price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('pub_date', models.CharField(max_length=100)),
                ('ib', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SEL', 'Selected'), ('DEL', 'Deleted')], default='NEW', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
