# Generated by Django 3.2.8 on 2021-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('area', models.IntegerField()),
                ('mt_price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('pub_date', models.CharField(max_length=100)),
                ('ib', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SEL', 'Selected'), ('DEL', 'Deleted')], default='NEW', max_length=3)),
            ],
        ),
    ]
